name: IPTV GitHub Scan and Push Task

on:
  # 1. 允许通过我们上面的 Worker 远程触发
  repository_dispatch:
    types: [trigger_iptv_scan]

  # 2. 同时也保留定时触发（比如每2小时，可选）
  schedule:
    - cron: '0 */2 * * *'

  # 3. 保留手动点击触发
  workflow_dispatch:

jobs:
  run_scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-level: '3.10'

      - name: Install dependencies
        run: |
          pip install aiohttp

      - name: Run Python Script
        env:
          PREFETCH_QUERIES: ${{ github.event.client_payload.prefetch_queries }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          PUSH_CALLBACK_URL: ${{ secrets.PUSH_CALLBACK_URL }}
          PUSH_API_KEY: ${{ secrets.PUSH_API_KEY }}
        run: |
          python main.py
