name: ZoomEye Push Task

on:
  # 1. 允许通过我们上面的 Worker 远程触发
  repository_dispatch:
    types: [trigger_zoomeye]

  # 2. 同时也保留定时触发（比如每2小时，可选）
#  schedule:
#    - cron: '0 */2 * * *'

  # 3. 保留手动点击触发
  workflow_dispatch:

jobs:
  run_scanner:
    runs-on: ubuntu-latest
    environment: "env"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  #  已修正为 python-version

      - name: Install deps
        run: |
          pip install playwright aiohttp
          playwright install chromium

      - name: Run Python Script
        env:
          PUSH_CALLBACK_URL: ${{ secrets.PUSH_CALLBACK_URL }}
          PUSH_API_KEY: ${{ secrets.PUSH_API_KEY }}
        run: |
          python .github/scripts/zoomeye.py
